sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=*S6851
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.tsx
sonar.issue.ignore.multicriteria=e2
sonar.issue.ignore.multicriteria.e2.ruleKey=*S6849
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.tsx
